services:
  yuzubot:
    user: 1000:1000
    container_name: yuzubot
    build: .
    volumes:
      - ./config.py:/app/config.py:ro
      - ./data/:/app/data/
      - ./cache/:/app/cache/
      - ./logs/:/app/logs/
