services:
  yuzubot:
    user: 1000:1000
    container_name: yuzubot
    build: .
    volumes:
      - ./config.py:/app/config.py:ro
      - ./data/:/app/data/
      - ./scripts/cache/:/app/scripts/cache
      - ./assets/discimg/cache/:/app/assets/discimg/cache
      - ./logs/:/app/logs/
